# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.EmailField(max_length=70)),
                ('library_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingroup',
            name='library_owner',
        ),
        migrations.DeleteModel(
            name='InGroup',
        ),
    ]
