# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ingroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingroup',
            name='library_owner',
        ),
        migrations.DeleteModel(
            name='InGroup',
        ),
    ]
