# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170713_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
