# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170713_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('b', 'Borrowed from'), ('l', 'Loaned to'), ('a', 'Available')], default='a', help_text='Book availability', max_length=1),
        ),
    ]
