# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
