# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_delete_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book_owner', 'book']},
        ),
    ]
