# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170716_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book']},
        ),
    ]
