# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0018_auto_20170716_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book_owner', 'book']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('b', 'Borrowed from'), ('f', 'From outside'), ('l', 'Loaned to'), ('o', 'On outside'), ('a', 'Available')], default='a', help_text='Book availability', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='bookinstance',
            unique_together=set([('book', 'book_owner')]),
        ),
    ]
