# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20170716_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, null=True, verbose_name='ISBN'),
        ),
    ]
