# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20170717_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
