# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20170717_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('b', 'Borrowed from'), ('f', 'From outside'), ('l', 'Loaned to'), ('o', 'On outside'), ('a', 'Available')], default='a', max_length=1),
        ),
    ]
