# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20170722_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrowed_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
