# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20170723_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['status', 'book']},
        ),
    ]
