# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20170723_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='now_reading',
            field=models.BooleanField(default=False),
        ),
    ]
