# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0037_bookinstance_now_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReadingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reading', models.DateField(default=datetime.date.today)),
                ('end_reading', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.BookInstance')),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_reading', 'book_instance'],
            },
        ),
    ]
