# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0038_bookreadinghistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookreadinghistory',
            unique_together=set([('book_instance', 'reader', 'start_reading')]),
        ),
    ]
