# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20170723_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreadinghistory',
            name='end_reading',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookreadinghistory',
            unique_together=set([]),
        ),
    ]
